name: Node.js Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  DATABASE_URL: '${{secrets.DATABASE_URL}}'
  NEXTAUTH_SECRET: '${{secrets.NEXTAUTH_SECRET}}'
  NEXTAUTH_URL: '${{secrets.NEXTAUTH_URL}}'
  DISCORD_CLIENT_ID: '${{secrets.DISCORD_CLIENT_ID}}'
  DISCORD_CLIENT_SECRET: '${{secrets.DISCORD_CLIENT_SECRET}}'
  OPENAI_SECRET_KEY: '${{secrets.OPENAI_SECRET_KEY}}'
  SKIP_ENV_VALIDATION: 1
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
      - uses: actions/checkout@v3
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'
          cache: npm
      - run: npm ci
      - run: npm run build --if-present
      - run: npx pm2 reload "rad"
